# Beginning NumPy

Install NumPy with:

conda install numpy

or /n

pip install numpy

numpy arrays come in two flavors
1. Vectors - 1D array
2. Matrices - 2D array

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
# Import the library for numpy
import numpy as np

In [4]:
# Making an array
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
# Making a matrix - list of lists
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8 ,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
# Making a matrix - NumPy argument for matrices
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# NumPy argument for defining a range of values
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
# Numpy argument for an array (or matrix) of zeroes
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5)) # first number m, second number n, or (down, across)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# NumPy argument for an array (or matrix) of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# NumPy argument for an array of values covering a space by a particular spacing between points
np.linspace(1, 11, 11)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [14]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# NumPy argument for an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# NumPy argument for random number arrays - radnom sample of uniform distribution from 0 to 1
np.random.rand(5)

array([0.32803697, 0.00599974, 0.75653082, 0.77122332, 0.79919891])

In [17]:
# Random Matrix - note the lack of tuple and only the dimension
np.random.rand(5,5)

array([[0.36703501, 0.92146534, 0.7209456 , 0.46951597, 0.81500337],
       [0.9838335 , 0.92147074, 0.29149245, 0.99465883, 0.28399391],
       [0.02483508, 0.73363156, 0.25187548, 0.56258614, 0.40782814],
       [0.07531277, 0.33810235, 0.85443922, 0.61149968, 0.99935629],
       [0.26664422, 0.51969991, 0.90659352, 0.31398037, 0.91833673]])

In [18]:
# NumPy argument for random number arrays - radnom sample of normal (Gaussian) distribution centered around zero
np.random.randn(2)

array([-1.00622823,  0.83625198])

In [19]:
# Random matrix - again only comma separated
np.random.randn(3,3)

array([[ 0.21647424,  1.37511251,  0.32617639],
       [-0.02926076,  0.41766483,  0.16579213],
       [ 0.47617504, -0.01338312,  0.86850186]])

In [20]:
# NumPy argument for random arrays - random integeres from a low to a high number
np.random.randint(1, 101, 10)

array([23, 84, 13, 11, 23, 73, 47, 48, 21, 83])

# Attributes and methods of an array

In [21]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([33, 32, 44, 47, 29, 46, 47,  4, 29,  4])

In [23]:
# Reshaping an array: nameOfArray.reshape(m,n)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# Dimensions must agree, no auto-inserting zeroes
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [25]:
# Return the maximum value of an array
ranarr.max()

47

In [26]:
# Return the minimum value of an array
ranarr.min()

4

In [27]:
# Return the location of the maximum value (index value)
ranarr.argmax()

3

In [28]:
# Return the location of the minimum value (index value)
ranarr.argmin()

7

In [29]:
# Notice the reshape didn't stick
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
# Just reassign it
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
# Find the shape of the matrix
arr.shape

(5, 5)

In [32]:
arr.dtype

dtype('int64')

In [33]:
# can also avoid having to type "np.BlahBlahBlah"
from numpy.random import randint
# see it in action
randint(2,10)

2

#
# End of Lecture 17
#

# NumPy Indexing and Selection

In [34]:
import numpy as np

In [35]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
# Using slice notation
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [39]:
# Return everything up to a certain value
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [40]:
# Return everything after a certain index - note that value = 5 is at index 6 not index 5
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
# NumPy arrays differ from python list because of their ability to broadcast
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
sliceOfArr = arr[0:6]
sliceOfArr

array([0, 1, 2, 3, 4, 5])

In [44]:
sliceOfArr[:] = 99
sliceOfArr

array([99, 99, 99, 99, 99, 99])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Note that changing sliceOfArr = arr[0:6] to sliceOfArr[:] = 99 adjusted arr in the segments where sliceOfArr was defined, particularly 0:6.
    
As arr was a NumPy array, it means that it differs from a Python list and therefore, when some variable is defined from it, that variable is only a view of the original array.

In [46]:
arrCopy = arr.copy()
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr == arrCopy

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [48]:
arrCopy[:] = 100
arr == arrCopy

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [49]:
# Create a 2D array
arr2D = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr2D.shape

(3, 3)

# Two formats for grabbing values from an array
1. Double bracket
2. Single bracket with a comma

In [51]:
# Double bracket format
arr2D
# Grab digit 5, it's in the first row first column
arr2D[0][0]

5

In [52]:
# Grab the value 40
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
arr2D[2][1]

40

In [54]:
# Return digit 30
arr2D[1][2]

30

In [55]:
# Return the second row
arr2D[1]

array([20, 25, 30])

In [56]:
# Single bracket with a comma
arr2D[:,1]

array([10, 25, 40])

In [59]:
arr2D[:,0]

array([ 5, 20, 35])

In [62]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
# Grabbing submatrices
# Top right corner
arr2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [63]:
# Bottom left
arr2D[1:,0:2]

array([[20, 25],
       [35, 40]])

In [64]:
arr2D[(0,2),:]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [65]:
arr2D[:,(0,2)]

array([[ 5, 15],
       [20, 30],
       [35, 45]])

# Lecture 19

In [66]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
boolArr = arr > 5
boolArr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [72]:
arr[boolArr]
# Only returns results where boolean results are true

array([ 6,  7,  8,  9, 10])

In [73]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [74]:
arr2D = np.arange(50).reshape(5,10)
arr2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [76]:
arr2D[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [77]:
arr2D[:,(0,2,4)]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34],
       [40, 42, 44]])

# Operations in NumPy

In [78]:
import numpy as np

In [79]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
add = arr + arr
subtract = arr - arr
multiply = arr * arr
print('Result of adding:',add)
print('Result of subtracting:',subtract)
print('Result of multiplying:',multiply)

Result of adding: [ 0  2  4  6  8 10 12 14 16 18 20]
Result of subtracting: [0 0 0 0 0 0 0 0 0 0 0]
Result of multiplying: [  0   1   4   9  16  25  36  49  64  81 100]


In [95]:
# element by element basis
addEW = arr + 100
subtractEW = arr - 100
multiplyEW = arr * 100
print('Result of elementwise adding:',addEW)
print('Result of elementwise subtracting:',subtractEW)
print('Result of elementwise multiplying:',multiplyEW)

Result of elementwise adding: [100 101 102 103 104 105 106 107 108 109 110]
Result of elementwise subtracting: [-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
Result of elementwise multiplying: [   0  100  200  300  400  500  600  700  800  900 1000]


In [97]:
# Numpy may only issues a warning instead of outputting an error on certain operations
1/0
# NOTE THE ERROR

ZeroDivisionError: division by zero

In [96]:
arr / arr
# NOTE THE 'nan' and lack of error

/Users/mbair/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [98]:
1 / arr
# NOTE THE 'inf' and lack of error

/Users/mbair/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [99]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# Universal array functions

In [100]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [101]:
# Exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [102]:
# maximum value
np.max(arr)

10

In [103]:
arr.max()

10

In [104]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [105]:
np.log(arr)
# runtime warning, but still runs and gives -inf

/Users/mbair/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# A series of exercises in NumPy

#### Import NumPy as np

In [107]:
import numpy as np

In [108]:
#### Create an array of 10 zeros 

In [110]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [111]:
#### Create an array of 10 ones

In [113]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [114]:
#### Create an array of 10 fives

In [115]:
arr = np.ones(10) * 5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [116]:
#### Create an array of the integers from 10 to 50

In [117]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [118]:
np.max(arr)

50

In [119]:
np.min(arr)

10

In [120]:
#### Create an array of all the even integers from 10 to 50

In [122]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [123]:
#### Create a 3x3 matrix with values ranging from 0 to 8

In [124]:
mat = np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [125]:
#### Create a 3x3 identity matrix

In [127]:
ident = np.eye(3)
ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [128]:
#### Use NumPy to generate a random number between 0 and 1

In [135]:
randInt = np.random.rand(1)
randInt

array([0.20645628])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [144]:
arr = np.random.randn(25,)
print(arr)
print(np.shape(arr))

[ 1.04803581  0.49067336 -0.06844302  1.03281862 -0.39769935  0.6431374
 -1.20533726  0.36567125 -0.84776339 -0.87108017  0.23501305  0.30599621
 -0.57170228 -1.11641505  1.31204486  0.94777928  0.64591924 -0.05632008
  2.35160835 -1.36047424 -1.57028829 -1.34591778  0.93172627  0.93666294
 -0.63117446]
(25,)


In [146]:
#### Create the following matrix: 10x10 with elements ranging from 0-1 by 0.01 step

In [150]:
mat = np.linspace(0.01,1,100).reshape(10,10)
mat

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [151]:
#### Create an array of 20 linearly spaced points between 0 and 1:

In [153]:
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [156]:
# 5x5 matrix from 1-25
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Now do the following
Get the sum of all the values in mat

In [158]:
added = mat.sum()

Get the standard deviation of the values in mat

In [160]:
standDev = np.std(mat)
standDev

7.211102550927978

In [ ]:
#### Get the sum of all the columns in mat

In [161]:
colSums = mat.sum(axis = 0)
colSums

array([55, 60, 65, 70, 75])